source 'https://github.com/rarnu/RarnuSpecs.git'


project 'WebContainer.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebContainer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for WebContainer
  pod 'WebViewJavascriptBridge'
  pod 'sfunctional'
end

target 'Sample' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for WebContainer
    pod 'WebViewJavascriptBridge'
    pod 'sfunctional'
end
